// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0--rc3
// source: proto/illustrator/illustrator.proto

package illustrator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IllustratorService_Create_FullMethodName = "/illustrator_service.IllustratorService/Create"
)

// IllustratorServiceClient is the client API for IllustratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IllustratorServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type illustratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIllustratorServiceClient(cc grpc.ClientConnInterface) IllustratorServiceClient {
	return &illustratorServiceClient{cc}
}

func (c *illustratorServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, IllustratorService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IllustratorServiceServer is the server API for IllustratorService service.
// All implementations must embed UnimplementedIllustratorServiceServer
// for forward compatibility
type IllustratorServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedIllustratorServiceServer()
}

// UnimplementedIllustratorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIllustratorServiceServer struct {
}

func (UnimplementedIllustratorServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedIllustratorServiceServer) mustEmbedUnimplementedIllustratorServiceServer() {}

// UnsafeIllustratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IllustratorServiceServer will
// result in compilation errors.
type UnsafeIllustratorServiceServer interface {
	mustEmbedUnimplementedIllustratorServiceServer()
}

func RegisterIllustratorServiceServer(s grpc.ServiceRegistrar, srv IllustratorServiceServer) {
	s.RegisterService(&IllustratorService_ServiceDesc, srv)
}

func _IllustratorService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IllustratorServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IllustratorService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IllustratorServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IllustratorService_ServiceDesc is the grpc.ServiceDesc for IllustratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IllustratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "illustrator_service.IllustratorService",
	HandlerType: (*IllustratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _IllustratorService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/illustrator/illustrator.proto",
}
